# Generated by Django 6.0.2 on 2026-03-06 03:16

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='банк')),
                ('adress', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='эл. почта')),
                ('bank_id', models.CharField(max_length=9, verbose_name='БИК')),
                ('inn', models.CharField(verbose_name='ИНН')),
                ('ogrn', models.CharField(unique=True, verbose_name='ОГРН')),
                ('c_a', models.CharField(default='', max_length=20, verbose_name='К/С')),
            ],
            options={
                'verbose_name': 'банк',
                'verbose_name_plural': 'банки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockOutProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'перечень отгрузки',
                'verbose_name_plural': 'перечни отгрузки',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('adress', models.CharField(max_length=100, verbose_name='адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='эл. почта')),
                ('inn', models.CharField(unique=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(unique=True, verbose_name='ОГРН')),
                ('bank_account', models.CharField(verbose_name='счёт в банке')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bank', verbose_name='банк')),
            ],
            options={
                'verbose_name': 'покупатель',
                'verbose_name_plural': 'покупатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OwnCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('adress', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='эл. почта')),
                ('inn', models.CharField(unique=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(unique=True, verbose_name='ОГРН')),
                ('bank_account', models.CharField(verbose_name='счёт в банке')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bank', verbose_name='банк')),
            ],
            options={
                'verbose_name': 'своя фирма',
                'verbose_name_plural': 'свои фирмы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='склад')),
                ('adress', models.CharField(max_length=100, verbose_name='адрес')),
                ('owner', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='store.owncompany', verbose_name='владелец склада')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, unique=True, verbose_name='наименование')),
                ('supplier_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='артикул')),
                ('measure_unit', models.CharField(choices=[('шт.', 'шт.'), ('кг.', 'кг.'), ('м.', 'м.'), ('кв.м.', 'кв.м.'), ('л.', 'л.'), ('уп.', 'уп.'), ('т.', 'т.'), ('куб.м.', 'куб.м.'), ('пог.м.', 'пог.м.')], verbose_name='ед.изм.')),
                ('VAT_tax', models.SmallIntegerField(blank=True, null=True, verbose_name='НДС')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='native_stock', to='store.stock', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='наименование')),
                ('supplier_id', models.CharField(db_index=True, max_length=30, verbose_name='артикул')),
                ('measure_unit', models.CharField(choices=[('шт.', 'шт.'), ('кг.', 'кг.'), ('м.', 'м.'), ('кв.м.', 'кв.м.'), ('л.', 'л.'), ('уп.', 'уп.'), ('т.', 'т.'), ('куб.м.', 'куб.м.'), ('пог.м.', 'пог.м.')], verbose_name='ед.изм.')),
                ('VAT_tax', models.SmallIntegerField(blank=True, null=True, verbose_name='НДС')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.stock', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'historical товар',
                'verbose_name_plural': 'historical товары',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_waybill_number', models.CharField(default='', max_length=30, verbose_name='№ накладной')),
                ('in_invoice_number', models.CharField(default='', max_length=30, verbose_name='№ счёта-фактуры')),
                ('in_waybill_date', models.DateField(verbose_name='Дата документа')),
                ('in_date', models.DateField(help_text='текущая дата оприходования', verbose_name='Дата')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Проведён')),
                ('comment', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Комментарий')),
                ('buyer', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='store.owncompany', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'поступление',
                'verbose_name_plural': 'поступления',
                'ordering': ['-in_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStockInProductItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='закупочеая цена')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='оптовая цена')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='розничная цена')),
                ('customs_declaration', models.CharField(blank=True, null=True, verbose_name='таможенная декларация')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.product', verbose_name='Товар')),
                ('stockin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.stockin')),
            ],
            options={
                'verbose_name': 'historical позиция прихода',
                'verbose_name_plural': 'historical позиции прихода',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockInProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='закупочеая цена')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='оптовая цена')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='розничная цена')),
                ('customs_declaration', models.CharField(blank=True, null=True, verbose_name='таможенная декларация')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_item', to='store.product', verbose_name='Товар')),
                ('stockin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_position', to='store.stockin')),
            ],
            options={
                'verbose_name': 'позиция прихода',
                'verbose_name_plural': 'позиции прихода',
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_waybill_number', models.SlugField(default='', max_length=15, verbose_name='№ накладной')),
                ('out_invoice_number', models.SlugField(default='', max_length=15, verbose_name='№ счёта-фактуры')),
                ('out_date', models.DateField(auto_now_add=True, verbose_name='Дата документа')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Проведён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(default='', max_length=50, verbose_name='Комментарий')),
                ('buyer', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='store.buyer', verbose_name='Покупатель')),
                ('supplier', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='store.owncompany', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'отгрузка',
                'verbose_name_plural': 'отгрузки',
                'ordering': ['-out_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('adress', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='эл. почта')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('inn', models.CharField(unique=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(unique=True, verbose_name='ОГРН')),
                ('bank_account', models.CharField(verbose_name='счёт в банке')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bank', verbose_name='банк')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stockin',
            name='supplier',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='store.supplier', verbose_name='Поставщик'),
        ),
    ]
