# Generated by Django 5.2.8 on 2025-12-03 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='банк')),
                ('adress', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='эл. почта')),
                ('bank_id', models.CharField(max_length=9, verbose_name='БИК')),
                ('inn', models.CharField(verbose_name='ИНН')),
                ('ogrn', models.CharField(unique=True, verbose_name='ОГРН')),
                ('c_a', models.CharField(default='', max_length=20, verbose_name='К/С')),
            ],
            options={
                'verbose_name': 'банк',
                'verbose_name_plural': 'банки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, max_length=30)),
                ('p_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'цена',
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, max_length=15)),
                ('q_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'количество',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('adress', models.CharField(max_length=100, verbose_name='адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='эл. почта')),
                ('inn', models.CharField(unique=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(unique=True, verbose_name='ОГРН')),
                ('bank_account', models.CharField(verbose_name='счёт в банке')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bank', verbose_name='банк')),
            ],
            options={
                'verbose_name': 'покупатель',
                'verbose_name_plural': 'покупатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OwnCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('adress', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='эл. почта')),
                ('inn', models.CharField(unique=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(unique=True, verbose_name='ОГРН')),
                ('bank_account', models.CharField(verbose_name='счёт в банке')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bank', verbose_name='банк')),
            ],
            options={
                'verbose_name': 'своя фирма',
                'verbose_name_plural': 'свои фирмы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='склад')),
                ('adress', models.CharField(max_length=100, verbose_name='адрес')),
                ('owner', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='store.owncompany', verbose_name='владелец склада')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, unique=True, verbose_name='наименование')),
                ('supplier_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='артикул')),
                ('measure_unit', models.CharField(choices=[('шт.', 'шт.'), ('кг.', 'кг.'), ('м.', 'м.'), ('кв.м.', 'кв.м.'), ('л.', 'л.'), ('уп.', 'уп.'), ('т.', 'т.'), ('куб.м.', 'куб.м.')], verbose_name='ед.изм.')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.stock', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SlugField(max_length=15, verbose_name='№')),
                ('out_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отгрузки')),
                ('buyer', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='store.buyer', verbose_name='Покупатель')),
                ('product', models.ManyToManyField(to='store.product', verbose_name='товары')),
                ('supplier', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='store.owncompany', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'отгрузка',
                'verbose_name_plural': 'отгрузки',
                'ordering': ['-out_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('adress', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='эл. почта')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('inn', models.CharField(unique=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(unique=True, verbose_name='ОГРН')),
                ('bank_account', models.CharField(verbose_name='счёт в банке')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bank', verbose_name='банк')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.SlugField(default='', max_length=15, verbose_name='№ накладной')),
                ('invoice_number', models.SlugField(default='', max_length=15, verbose_name='№ счёта-фактуры')),
                ('in_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время поступления')),
                ('stock_in_total', models.IntegerField(default=0, verbose_name='Сумма документа')),
                ('comment', models.CharField(default='', max_length=50, verbose_name='Комментарий')),
                ('buyer', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='store.owncompany', verbose_name='Покупатель')),
                ('supplier', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='store.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'поступление',
                'verbose_name_plural': 'поступления',
                'ordering': ['-in_date'],
            },
        ),
    ]
