# Generated by Django 5.2.5 on 2025-09-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='название')),
                ('adress', models.CharField(max_length=100, null=True, unique=True, verbose_name='адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('bank_id', models.IntegerField(verbose_name='БИК')),
                ('inn', models.IntegerField(null=True, verbose_name='ИНН')),
                ('ogrn', models.IntegerField(null=True, unique=True, verbose_name='ОГРН')),
            ],
            options={
                'verbose_name': 'банк',
                'verbose_name_plural': 'банки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'ед. изм.',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_number',
            field=models.SlugField(help_text='уникальный ID товара', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='adress',
            field=models.CharField(blank=True, max_length=100, verbose_name='адрес'),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='название')),
                ('adress', models.CharField(max_length=100, null=True, unique=True, verbose_name='адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('inn', models.IntegerField(null=True, unique=True, verbose_name='ИНН')),
                ('ogrn', models.IntegerField(null=True, unique=True, verbose_name='ОГРН')),
                ('bank_account', models.IntegerField(verbose_name='счёт в банке')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.bank', verbose_name='банк')),
            ],
            options={
                'verbose_name': 'покупатель',
                'verbose_name_plural': 'покупатели',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='measure_unit',
            field=models.ForeignKey(default='шт.', max_length=10, on_delete=django.db.models.deletion.DO_NOTHING, to='store.measureunit', verbose_name='ед. изм.'),
        ),
        migrations.CreateModel(
            name='OwnCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='название')),
                ('adress', models.CharField(max_length=100, null=True, unique=True, verbose_name='адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('inn', models.IntegerField(null=True, unique=True, verbose_name='ИНН')),
                ('ogrn', models.IntegerField(null=True, unique=True, verbose_name='ОГРН')),
                ('bank_account', models.IntegerField(verbose_name='счёт в банке')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.bank', verbose_name='банк')),
            ],
            options={
                'verbose_name': 'своя фирма',
                'verbose_name_plural': 'свои фирмы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='owner',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.owncompany', verbose_name='владелец склада'),
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SlugField(max_length=15, verbose_name='№')),
                ('out_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время отгрузки')),
                ('buyer', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.buyer', verbose_name='Покупатель')),
                ('product', models.ManyToManyField(to='store.product', verbose_name='товары')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.stock')),
                ('supplier', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.owncompany', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'отгрузка',
                'verbose_name_plural': 'отгрузки',
                'ordering': ['-out_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='название')),
                ('adress', models.CharField(max_length=100, null=True, unique=True, verbose_name='адрес')),
                ('phone_number', models.CharField(max_length=15, verbose_name='тел.')),
                ('inn', models.IntegerField(null=True, verbose_name='ИНН')),
                ('ogrn', models.IntegerField(null=True, unique=True, verbose_name='ОГРН')),
                ('bank_account', models.IntegerField(verbose_name='счёт в банке')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.bank', verbose_name='банк')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SlugField(max_length=15, verbose_name='№')),
                ('in_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время поступления')),
                ('buyer', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.owncompany', verbose_name='Покупатель')),
                ('product', models.ManyToManyField(to='store.product', verbose_name='товары')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.stock')),
                ('supplier', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'поступление',
                'verbose_name_plural': 'поступления',
                'ordering': ['-in_date'],
            },
        ),
    ]
