# Generated by Django 5.2.5 on 2025-09-03 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_bank_measureunit_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.DO_NOTHING, to='store.measureunit', verbose_name='ед. изм.'),
        ),
    ]
