# Generated by Django 5.2.5 on 2025-09-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.measureunit', verbose_name='ед. изм.'),
        ),
    ]
