# Generated by Django 5.2.5 on 2025-09-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_id_alter_product_item_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_number',
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='банк'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(help_text='уникальный ID товара', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='склад'),
        ),
    ]
