# Generated by Django 5.2.5 on 2025-09-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_item_number_alter_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measure_unit',
        ),
        migrations.DeleteModel(
            name='MeasureUnit',
        ),
    ]
