# Generated by Django 5.2.5 on 2025-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_measureunit_alter_product_id_product_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(help_text='уникальный ID товара', primary_key=True, serialize=False),
        ),
    ]
